import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar/NavBar';
import { ToastContainer } from 'react-toastify';
import { AuthProvider } from '@/provider/AuthProvider';

export const metadata: Metadata = {
    title: 'IMCI',
    description: 'Generated by create next app',
};

const roboto = Roboto({
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${roboto.className} antialiased`}>
                <AuthProvider>
                    <ToastContainer />
                    <NavBar />
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}
